apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        costcernter: amer
        location: USA
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3