apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-07-26T13:12:45Z"
  generation: 1
  labels:
    app: httpd-frontned
  name: httpd-frontned
  namespace: default
  resourceVersion: "1355988"
  uid: 6c4f0fe5-8843-418b-b2aa-33ab6b273c46
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd-frontned
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-frontned
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}