apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: develuser-developer-RoleBinding
subjects:
  - kind: User
    name: dev-User
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
