apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    costcernter: amer
    location: USA
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
