apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  namespace: default
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log